create_clock -name clk -period 20 -waveform {0 10} [get_ports {clk}]
create_clock -name clk50 -period 20 -waveform {0 10} [get_ports {netrmii_clk50m}]
create_clock -name clk1 -period 1000 -waveform {0 500} [get_nets {netrmii_mdc}]
set_false_path -from [get_clocks {clk1}] -to [get_clocks {clk50}] 
set_false_path -from [get_clocks {clk50}] -to [get_clocks {clk1}] 
